name: ci

on:
  push:
    branches:
      - release-dr

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - uses: actions/checkout@master

      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      - run: npm run build
      
      - name: Deploy over SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          source: "./public/build/*"
          target: "/home/deploy/test"
